added background image
js-tasks-ru/htmlcss-20220811_dem pull request #12
Opened 2022-08-29 13:32 UTC by demansh

2022-08-29 13:33 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-08-30 14:04 UTC, GSemikozov requested changes

2022-08-30 14:04 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +@media (max-width: 480px) {
лишний медиа-запрос, это стили применяющиеся по умолчанию

2022-08-30 14:04 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +@media (min-width: 480px) and (max-width: 768px) {
если это mobile first, то max-width везде проставлять не надо

2022-08-30 14:04 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +        background-repeat:no-repeat;
и дублировать background-repeat + background-size тоже не надо

2022-08-30 18:41 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-01 11:46 UTC, demansh commented on 06-lection4/02-background-image/background-image.css
> +@media (max-width: 480px) {
поправил

2022-09-01 11:46 UTC, demansh commented on 06-lection4/02-background-image/background-image.css
> +@media (min-width: 480px) and (max-width: 768px) {
поправил

2022-09-01 11:46 UTC, demansh commented on 06-lection4/02-background-image/background-image.css
> +        background-repeat:no-repeat;
поправил

2022-09-01 11:46 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-01 15:44 UTC, GSemikozov approved these changes

2022-09-01 15:45 UTC, GSemikozov approved these changes

2022-09-01 15:45 UTC, merged